### ISSUE TITLE
J1<->J2 traffic stops when connecting a cable to J4

### ISSUE THREAD

**Issue by yanshay** [greatscottgadgets/throwing-star-lan-tap#9] opened 2021-11-20 13:31 UTC
I bought Throwing Star Lan Tap on Amazon.

I connect the traffic cables to J1 and J2, and communication works fine with only those connected.

Once I connect a cable to J4 communication between J1 and J2 hangs. It hangs when just connecting a cable with nothing connected to its other end. I checked this with several different cables that all are working fine.
If I connect it to a machine with wireshark, I can see packets on J4 at that time.

If I connect a cable to J3 communication sometimes hangs up but not always. 
And if I try to capture with wireshark then I don't see any traffic.

Any ideas what could cause this behavior? 
Is that a faulty lan tap I received?

Thanks

**Comment by gozu42** [comment] 2021-11-20 13:43
can you please post the output of ethtool on one (or even better both) sides of the link in both working and not working situation?
how long are the involved cables?

**Comment by yanshay** [comment] 2021-11-20 16:10
One side (J2) is a switch so I can run only on the other side (J1) (rasbperry pi).

Below is ethtool output with no cable connected, with cable connected on J4 and with cable connected on J3

--- With No Cable Connected ---
Settings for eth0:
	Supported ports: [ TP MII ]
	Supported link modes:   10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Half 1000baseT/Full
	Supported pause frame use: Symmetric Receive-only
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Half 1000baseT/Full
	Advertised pause frame use: Symmetric Receive-only
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Link partner advertised link modes:  10baseT/Half 10baseT/Full
	                                     100baseT/Half 100baseT/Full
	Link partner advertised pause frame use: Symmetric Receive-only
	Link partner advertised auto-negotiation: Yes
	Link partner advertised FEC modes: Not reported
	Speed: 100Mb/s
	Duplex: Full
	Port: Twisted Pair
	PHYAD: 1
	Transceiver: internal
	Auto-negotiation: on
	MDI-X: Unknown
	Supports Wake-on: gsf
	Wake-on: d
        SecureOn password: 00:00:00:00:00:00
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes

--- With cable connected to J4 ---
Settings for eth0:
	Supported ports: [ TP MII ]
	Supported link modes:   10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Half 1000baseT/Full
	Supported pause frame use: Symmetric Receive-only
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Half 1000baseT/Full
	Advertised pause frame use: Symmetric Receive-only
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Speed: Unknown!
	Duplex: Unknown! (255)
	Port: Twisted Pair
	PHYAD: 1
	Transceiver: internal
	Auto-negotiation: on
	MDI-X: Unknown
	Supports Wake-on: gsf
	Wake-on: d
        SecureOn password: 00:00:00:00:00:00
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: no

--- With cable connected on J3 (and now this didn't cause a network disconnect, also ethtool seems to show the same as w/o cable connected but I still post the output) ---

Settings for eth0:
	Supported ports: [ TP MII ]
	Supported link modes:   10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Half 1000baseT/Full
	Supported pause frame use: Symmetric Receive-only
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  10baseT/Half 10baseT/Full
	                        100baseT/Half 100baseT/Full
	                        1000baseT/Half 1000baseT/Full
	Advertised pause frame use: Symmetric Receive-only
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Link partner advertised link modes:  10baseT/Half 10baseT/Full
	                                     100baseT/Half 100baseT/Full
	Link partner advertised pause frame use: Symmetric Receive-only
	Link partner advertised auto-negotiation: Yes
	Link partner advertised FEC modes: Not reported
	Speed: 100Mb/s
	Duplex: Full
	Port: Twisted Pair
	PHYAD: 1
	Transceiver: internal
	Auto-negotiation: on
	MDI-X: Unknown
	Supports Wake-on: gsf
	Wake-on: d
        SecureOn password: 00:00:00:00:00:00
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes

**Comment by yanshay** [comment] 2021-11-20 16:12
Oh, forgot to answer on the cables length, not long ones - around 1 meter ( I tried also with a longer cable around 6m and same behavior)

**Comment by yanshay** [comment] 2021-11-21 21:37
I found a way to workaround the issue for now - I used two 100mbps switches (so such that don't support 1Gbps) between the switch and the raspberry PI and also used short cables and that allowed me to do the traffic sniffing. Pretty cumbersome but worked.

**Comment by straithe** [comment] 2021-11-29 19:20
I'm happy to hear you found a solution, and I'm sorry I didn't get back to you sooner (I was on vacation). Are you happy with your solution, or would you like more support?

**Comment by yanshay** [comment] 2021-11-30 19:23
My solution is very cumbersome and actually made me think I should purchase a managed switch for a more acceptable usage. If there's a way to solve this it would be great but seems to me it's caused by some specific equipment I'm using with which this device doesn't work.

**Comment by gozu42** [comment] 2021-11-30 19:32
> My solution is very cumbersome and actually made me think I should purchase a managed switch for a more acceptable usage.

i can recommend the netgear GS108T series switches as sniffing adapters. compact, no fan, 1Gbps, port mirroring. (also vlans, multicast, and a lot of other premium/managed features)

> If there's a way to solve this it would be great but seems to me it's caused by some specific equipment I'm using with which this device doesn't work.

an issue common to all "passive" sniffing adapters. they do horrible things to the signal quality/path (by design), so its always possible to get unlucky and have it push more sensitive devices "over the edge" into not working.

**Comment by yanshay** [comment] 2021-11-30 23:14
> i can recommend the netgear GS108T series switches as sniffing adapters. compact, no fan, 1Gbps, port mirroring. (also vlans, multicast, and a lot of other premium/managed features)

I was actually thinking about TP-Link TL-SG108E which I found much cheaper at Amazon, any difference between the two?

**Comment by mossmann** [comment] 2021-12-08 20:13
> Once I connect a cable to J4 communication between J1 and J2 hangs. It hangs when just connecting a cable with nothing connected to its other end.

Have you tried plugging in the other end of the cable before connecting it to J4 (or J3)? Unterminated cables connected to the monitoring ports can introduce reflections that cause problems with communications on the target network segment.

**Comment by straithe** [comment] 2022-01-28 07:06
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.

**Closed as completed by straithe** 2022-01-28 07:06 UTC
Labels: technical support

**Comment by chrispersonal** [comment] 2022-02-13 20:34
Glad I found this thread. I have been experiencing this exact same issue and am looking to understand what is going on more. My scenario is similar as OP. Tap is installed inline without issues (my use case is tapping a printer feed which is from a WinPC -> USB/Ethernet adapter -> Cat5e -> Tap -> ThermalPrinter). However, as soon as I plug in to J3 or J4, the printer disconnects and the ethernet activity lights stop indicating traffic. 

Until I found this thread I had no idea what was going on and was trying various combinations of connecting all the cables. It wasn't until I realized ([from this thread comment](https://github.com/greatscottgadgets/throwing-star-lan-tap/issues/9#issuecomment-989160595)) that the line plugged into J3 or J4 had to be terminated (in my case to a Eth/USB adapter into a monitoring PC) that the issue would go away.

The problem this presents is that if the monitoring PC is disconnected from the line connected to J3 or J4, the link between the PC and printer is broken. In a lab environment, no big deal. In the environment I am working in where the printer is used for Production purposes, its a big deal to have to access the printer to unplug the J3 or J4 (or the Tap entirely) every time.

I did basic reading on the reflection issue with unterminated ends, but most of what I could find had to do with Coaxial applications. I am not understanding what is going on here exactly. I'd like to find a solution so that the Tap can remain installed permanently and the end of the cable connected to J3/J4 can also be disconnected as needed without disruption.

Any suggestions on how to temporarily "terminate" the cable, or otherwise make adjustments to prevent this from happening would be appreciated. Thank you.
